-- La main courante des incidents : le seul registre de la taverne qui ne s'efface jamais.
-- Flyway crée le schéma main_courante (quarkus.flyway.schemas) et y tient son historique.

CREATE TABLE incident (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ouvertLe    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closLe      TIMESTAMP(6) WITH TIME ZONE,
    statut      VARCHAR(20)                 NOT NULL,
    declencheur VARCHAR(500)                NOT NULL
);

CREATE TABLE fait_marquant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT                      NOT NULL REFERENCES incident (id),
    horodatage  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    type        VARCHAR(30)                 NOT NULL,
    cle         VARCHAR(200),
    detail      VARCHAR(1000),
    valeur      BIGINT
);

CREATE INDEX fait_marquant_incident ON fait_marquant (incident_id, horodatage);
